import React from 'react'
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Home Section",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="hero-section flex flex-wrap justify-center items-center max-md:flex-col p-10 max-md:p-5">
        {/* Left Box */}
        <div className="left-box min-h-[200px] max-md:text-center md:w-1/2 w-full">
          <h1 className="text-blue-600 font-bold text-4xl md:text-3xl max-md:text-2xl mb-4">
            This Blog website created by Aayush
          </h1>
          <p className="text-gray-600 mb-8 p-4 max-md:p-0">
            Discover insights, tutorials, and the latest trends in web development.
            <br /> Whether youre a beginner or experienced coder, explore content
            <br /> that fuels your passion and keeps you ahead in the tech world.
          </p>
          <button className="bg-red-500 hover:bg-red-600 text-white p-4 rounded-2xl shadow-md transition-all duration-300 transform hover:scale-105">
            Get Started
          </button>
        </div>
  
        {/* Right Box */}
        <div className="right-box flex justify-center md:w-1/2 w-full mt-8 md:mt-0">
          <div className="developer-image">
            <img
              className="h-[300px] object-cover rounded-xl shadow-lg transition-all duration-300 transform hover:scale-105"
              src="https://img.freepik.com/free-vector/hand-drawn-web-developers_23-2148819604.jpg"
              alt="developer image"
            />
          </div>
        </div>
      </div>
    </main>
  );
  
}

export default page